[[labels]]
name = "label A 👯"
color = "ff0000"
description = "hoge"

[[labels]]
name = "label B :bug:"
color = "0000ff"
description = "fuga"

[issue]
template = """
## issue template

awesome issue

"""

[pull_request]
template = """
## pull request template

awesome code

"""
