[[labels]]
name = "label C"
color = "ff0000"
description = "hoge"

[[labels]]
name = "label D"
color = "0000ff"
description = "fuga"

[template]
issue = """
## issue template

awesome issue

"""

pull_request = """
## pull request template

awesome code

"""
